### ISSUE TITLE
0-RTT text is a bit obtuse

### ISSUE THREAD

**Issue by LPardue** [DavidSchinazi/draft-h3-datagram#14]
```
When servers decide to accept 0-RTT data, they MUST send a
H3_DATAGRAM SETTINGS parameter greater or equal to the value they sent to the
client in the connection where they sent them the NewSessionTicket
message.
```

In layspeak I think this is saying "if a server sent the value 1 before, it MUST send 1 now. If a server sent 0 before, it MUST send 0 or 1 now". 

Could we maybe editorialize this to make it less likely for someone to do `value++` and end up sending `2`?

**Comment by DavidSchinazi** [comment]
There is text in the doc stating that only 0 and 1 are valid. But I do agree that the current text is somewhat clunky. Can you send a PR?

**Comment by LPardue** [comment]
Sure, I'll make a PR.
