### ISSUE TITLE
Consider a different error code when the flow ID doesn't fit in the frame

### ISSUE THREAD

**Issue by LPardue** [DavidSchinazi/draft-h3-datagram#15]
There's some good guidance about parsing the Flow ID out of the HTTP/3 Datagram with respect to datagram payload length. But I'm not sure if the recommend error code of PROTOCOL_VIOLATION is the most appropriate. This implies that the error is a Transport Error but I'd argue that at this point (parsing of the frame payload) that its an HTTP/3 Application error. 

Since we're not actually parsing a true HTTP/3 frame, just a view over a transport frame, H3_FRAME_ERROR seems too specific. So I think H3_GENERAL_PROTOCOL_ERROR is the most straightforward.

I wonder what others think.

**Comment by DavidSchinazi** [comment]
I honestly am fine with any error for this, though I'd prefer to reuse an existing one to reduce complexity.
