### ISSUE TITLE
Register a setting

### ISSUE THREAD

**Issue by martinthomson** [DavidSchinazi/draft-h3-datagram#5]
In order to use this, this will need to be signaled somehow.  It seems like the draft infers that the presence of the transport parameter for DATAGRAM is sufficient, but I don't believe that to be the case.

Take the case where a client offers three protocols for use via ALPN.  One of those might always include DATAGRAM support and so the client is obligated to offer the transport parameter.  But that does not imply that all three offered protocols support this extension equally.  You need a way to unambiguously signal that the combination of DATAGRAM and h3 are supported.  That means a setting.

**Comment by DavidSchinazi** [comment]
I agree. I'll add a SETTING.

**Comment by DavidSchinazi** [comment]
Fixed via fd6e79923ca5fc0c22730d29abd5bbde2948bed1
