### ISSUE TITLE
"0-length" DATAGRAMS

### ISSUE THREAD

**Issue by LPardue** [DavidSchinazi/draft-h3-datagram#8]
Since DATAGRAMS can have a 0-length payload, and H3 DATAGRAM mandates a flow ID, then something should be said about how an endpoint treats this.

My first reaction is that this is a connection error of type H3_FRAME_ERROR.

**Comment by LPardue** [comment]
This should also be extended to the frame being too short to decode varint.

**Comment by DavidSchinazi** [comment]
I agree, failing to parse the varint flow ID due to the DATAGRAM payload being too short is indicative of a serious malfunction in the peer's h3-datagram implementation, so closing the connection sounds reasonable.

**Comment by DavidSchinazi** [comment]
This should be fixed in today's update to the drafts.
