### ISSUE TITLE
Field:Flow ID cardinality

### ISSUE THREAD

**Issue by martinthomson** [DavidSchinazi/draft-h3-datagram#9]
It's not really clear whether there are any expectations in relation to cardinality of flow identifiers and the field.  Can two fields refer to the same flow ID?  Can the same request reference multiple flow IDs?

**Comment by DavidSchinazi** [comment]
I think the h3 datagram draft should allow both:
- two requests can reuse the same flow ID if the definition of that HTTP features allows it (this feature is used by the [QUIC extension to CONNECT-UDP](https://tools.ietf.org/html/draft-pauly-masque-quic-proxy))
- one request can reference two flow IDs - I think this is already stated though:
> For example, an HTTP method that wishes to use two datagram flow identifiers for the lifetime of its request stream could encode the second flow identifier as a parameter

**Comment by martinthomson** [comment]
I'm sure that people operating intermediaries might have something to say here.  A gateway that routes flows might be unwilling to replicate datagram flows that are bound to requests that go to different origin servers.

I agree that one request to many flows is worthwhile, but mention in examples doesn't really count as a specification.

**Comment by DavidSchinazi** [comment]
Fair enough, I'll add text to make this clearer. And I'll add a note to the intermediaries section about how the intermediary needs to ensure that if a second request arrives that shares a flow ID with a previous one, the intermediary MUST either send the new request to the same backend or reject it.
